### ISSUE TITLE
Importing certain modules cause syntax errors in transpiled output

### ISSUE THREAD

**Issue by Elberet** [r-murphy/babel-plugin-transform-modules-ui5#14]
When importing modules such as `import "@babel/polyfill"`, the local variable name generated by `babel-plugin-transform-modules-ui5` is not correct syntax:

Example:
```js
import "@babel/polyfill"
```

Result:
```js
sap.ui.define(["@babel/polyfill"], function(__@babel_polyfill) {
  // ...
});
```

The `@` is not allowed here.

**Comment by r-murphy** [comment]
Fixed in rc4

**Comment by Elberet** [comment]
Thanks! 😄
