### ISSUE TITLE
Move Babel helpers into the sap.ui.define wrapper if possible

### ISSUE THREAD

**Issue by Elberet** [r-murphy/babel-plugin-transform-modules-ui5#17]
Babel replaces certain keywords with function calls when the semantics have changed between language versions. For example, `typeof(id)` gets transpiled to `_typeof(id)` and `function _typeof(obj) { /* magic */ }` (which handles `typeof(Symbol()) === "symbol"`s in older browsers) is injected near the top of the file.

The builder from `@ui5/project` expects that modules have an empty top level scope except for the `sap.ui.define` call. However, the babel-created `_typeof` function counts as a symbol in that scope; this yields a warning message:

> `WARN lbt:bundle:Builder **** warning: module app/Component.js requires top level scope and can only be embedded as a string (requires 'eval')`

This is probably not a very serious error. "Requires 'eval'" refers to the UI5 loader having to `eval` a string read from the generated preload file, so there's no security issue either.

Still, would it be possible to move these Babel-generated functions into the `sap.ui.define` factory if all other code was wrapped into the factory anyways? Is this perhaps related to #15 and the injected `import`s?

**Comment by r-murphy** [comment]
Should be fixed by #15 also.

**Comment by Elberet** [comment]
Looks good, the Babel helpers are now getting wrapped in the factory function as expected. 👍
