### ISSUE TITLE
Instance property initializers aren't always moved to the constructor when necessary

### ISSUE THREAD

**Issue by Elberet** [r-murphy/babel-plugin-transform-modules-ui5#18]
Consider this example:

```javascript
import * as Util from "./lib/util"
import Controller from "sap/ui/core/mvc/Controller"
@namespace("app")
export default class AppController extends Controller {
  static metadata = { /* ... */ }
  onClick = Util.debounce(100, () => this.onClickDebounced())
  onClickDebounced() {
    console.log("click!")
  }
}
```

In the example above, the `onClick` initializer is not moved into the constructor:

```javascript
sap.ui.define([/* ... */], function(Controller, Util) {
  var _this = this;

  var App = Controller.extend("app.AppController", {
    // ...
    onClick: Util.debounce(100, function() {
      return _this.onClickDebounced();
    })
    // ...
  });
  return App;
});
```

From what I can see, the initializer is moved only when `this` is accessed in the initializer's scope. When `this` is accessed in a lambda expression (which binds `this` lexically and thus inherits it from the outer scope), the initializer isn't moved and gets transpiled as though it were on the UI5 factory method's scope.

I have a sneaking suspicion that this is related to the changed discussed in #15 as well, because as long as the argument to `debounce()` does not have to be transpiled, the initializer gets moved as intended. For example, `onClick = Util.debounce(100, function(){ this.onClickDebounced(); }.bind(this))` works correctly...

**Comment by r-murphy** [comment]
Hey @Elberet . I fixed this in 7.0.0-rc7.
It was unrelated to #15. The check for `this` was not traversing into arrow functions. Based on the comment I made originally, it was an intentional omission, but I should I have left a TODO to go back to it.

**Comment by Elberet** [comment]
Awesome! But before I grab the new RC and test it - are you sure that checking for `this` is actually the right approach?

For example:

```js
import Control from "sap/ui/core/Control"
export default class Frob extends Control {
  clickTimestamps = []
  onClick() { this.clickTimestamps.push(Date.now()); }
}
```

People unfamiliar with how the plugin converts classes into `.extend` calls will probably not see any problem here, but in reality, as per the UI5 spec, `clickTimestamp` is added to the class' prototype. Since no instance of the class *writes* its own value, *all instances of `Frob` access and modify the same `clickTimestamps` array*.

Clearly, this isn't intended. This is why the prototype object should never contain any mutable values.

Based on that premise, the only initializers that can safely remain on the prototype are number literals, string literals, symbols, `true`, `false`, `null`, `undefined` and `NaN`. Everything else is either mutable, might return a mutable value, or might have a side-effect that would behave differently when the class is declared vs. when the class is instantiated.

**Comment by r-murphy** [comment]
It took me a bit to get to reproducing this situation. It looks like you are correct that `clickTimestamps` is shared being instances of the controller, which is likely not the expected behaviour. 

I'm going to change the default behaviour and I'll introduce an option to keep the old. Good think v7 is still in rc so I can set the default to the one without a gotcha. I may add special logic (if it's not already there) for `metadata` and `renderer` props, but with a warning.

**Comment by Elberet** [comment]
Are we talking about static or instance props `metadata` and `renderer`? For the static variant, those absolutely need special treatment so that UI5's `extend`-method does the right thing, but for the instance variant I beleive that neither is any special treatment required nor is there a reason to emit warnings.

After all, there's no technical reason why an object shouldn't be allowed to have a `this.metadata` property (it doesn't clash with `this.getMetadata()` after all) - and complaining about potentially misleading names is a job for an eslint plugin, not a Babel plugin. :wink:

**Comment by r-murphy** [comment]
I was referring to instance props `metadata` and `renderer`. I agree with you technically that they shouldn't have special treatment. I was just hoping to avoid breaking changes in some of my own apps ;) 

You've convinced me that 'correct' is better. I'll go with the option to keep the old behaviour and default to the correct behaviour to move all instance props.

**Comment by r-murphy** [comment]
Updated in rc8 with the new default behaviour. Let me know if you encounter any issues.

**Comment by Elberet** [comment]
I have two somewhat arcane observations:

1. Babel by default defines properties with a helper function that attempts to set non-writeable but reconfigurable properties through `Object.defineProperty()`, while this plugin "only" generates simple assignments. This is probably not a problem unless the user does something funny (e.g. override the new class' `.extend` class method after UI5 has decided to define that as a non-writeable property).

2. This is accepted without error:
   ```js
   const name = Symbol("_name")
   class Test extends Controller {
     [name] = null
   }
   ```
   However, the output will contain `this.name = null;`. Assuming that calculated property names in instance property initializers are even a thing, this is wrong; and assuming that this syntax is invalid, it should raise an error instead of generating unexpected code.

**Comment by r-murphy** [comment]
1. I'd be open to using Object.defineProperty(). Did you mean for class properties or for adding properties to the return object? If this is definitely something you want, it's probably better to add an issue for it, otherwise, I may not get to it.

2. I created #21 for this issue.

**Comment by Elberet** [comment]
I'm strictly referring to JS properties on the instance (`this.prop`) or class (`AppController.prop`) objects; I believe UI5 properties via the `metadata` configuration object should be well outside the scope of a code transpiler.

By the way, Babel has a helper for setting properties on an object, so why not just use that?
