### ISSUE TITLE
'const exports' templates are not transformed by preset-env

### ISSUE THREAD

**Issue by GuillaumedesPommareSAP** [r-murphy/babel-plugin-transform-modules-ui5#24]
Hello,

I am trying to transform a Typescript enum into a ui5/js resource compatible with IE11 ^^

For that I need this babel configuration: 
```
{
    "ignore": [
        "**/*.d.ts"
    ],
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": ["last 2 Chrome versions", "last 2 Firefox versions", "last 2 Edge versions", "ie >= 11"],
                "debug": true
            }
        ],
        "transform-ui5",
        "@babel/preset-typescript"
    ],
    "plugins": [
        [
            "@babel/plugin-proposal-class-properties"
        ],
        [
            "@babel/plugin-syntax-decorators",
            {
                "legacy": true
            }
        ]
    ]
}
```

The TS file is defined as follows:
```
export enum SessionFailure {

    INVALID_LOGIN_OR_PASSWORD = 0
}
```

And the resulting js is:
```
"use strict";

sap.ui.define([], function () {
  var SessionFailure;

  (function (SessionFailure) {
    SessionFailure[SessionFailure["INVALID_LOGIN_OR_PASSWORD"] = 0] = "INVALID_LOGIN_OR_PASSWORD";
  })(SessionFailure || (SessionFailure = {}));

  const __exports = {
    __esModule: true
  };
  __exports.SessionFailure = SessionFailure;
  return __exports;
});
```

My issue is that preset-env is tranforming all my *const* or *let* declarations into *var*. No issue with that. **Even SessionFailure itself is transformed.** BUT "const __exports = {" is not taken into account. Which causes many issue in further processing steps in my build.

I know that const exports is a template from this preset. I am not sure if here I am making a bug report or only a bad use of this preset. Could you help me ?

Thanks.
Guillaume

**Comment by GuillaumedesPommareSAP** [comment]
Hello,

I am trying to transform a Typescript enum into a ui5/js resource compatible with IE11 ^^

For that I need this babel configuration: 
`{
    "ignore": [
        "**/*.d.ts"
    ],
    "presets": [
        [
            "@babel/preset-env",
            {
                "targets": ["last 2 Chrome versions", "last 2 Firefox versions", "last 2 Edge versions", "ie >= 11"],
                "debug": true
            }
        ],
        "transform-ui5",
        "@babel/preset-typescript"
    ],
    "plugins": [
        [
            "@babel/plugin-proposal-class-properties"
        ],
        [
            "@babel/plugin-syntax-decorators",
            {
                "legacy": true
            }
        ]
    ]
}`

The TS file is defined as follows:
`export enum SessionFailure {

    INVALID_LOGIN_OR_PASSWORD = 0
}
`

And the resulting js is:
`"use strict";

sap.ui.define([], function () {
  var SessionFailure;

  (function (SessionFailure) {
    SessionFailure[SessionFailure["INVALID_LOGIN_OR_PASSWORD"] = 0] = "INVALID_LOGIN_OR_PASSWORD";
  })(SessionFailure || (SessionFailure = {}));

  const __exports = {
    __esModule: true
  };
  __exports.SessionFailure = SessionFailure;
  return __exports;
});
`

My issue is that preset-env is tranforming all my const or let declarations into var. No issuer with that. Even SessionFailure itself is transformed. BUT "const __exports = {" is not taken into account. Which causes many issue in further processing steps in my build.

I know that const exports is a template from this preset. I am not sure if here I am making a bug report or only a bad use of this preset. Could you help me ?

Thanks.
Guillaume

**Comment by r-murphy** [comment]
@GuillaumedesPommareSAP can you try changing the order of the top 2 presets?

For me it works in this order:

```
module.exports = {
  "presets": [
    ["babel-preset-transform-ui5", {
      "noImportInteropPrefixes": ["sap/", "demo/"],
      "moveControllerPropsToOnInit": true,
      "onlyConvertNamedClass": true,
      "addControllerStaticPropsToExtend": true
    }],
    ["@babel/preset-env", {
      "targets": {
        "chrome": 70,
        ie: 11
      },
      modules: false,
      useBuiltIns: "usage"
    }],
    "@babel/preset-typescript",
  ],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
};

```

**Comment by GuillaumedesPommareSAP** [comment]
Hello @r-murphy :)

Thanks for your message ! I tried this configuration but without success.
I created a repo to help "reproduce" my issue. This is not an exact replica of what I am doing but it is close enough and generates my issue: https://github.com/GuillaumedesPommareSAP/check_const_var

You will see there that the configuration is almost what you shared with me. I can do an exact copy of your config, I will have the same issue.

Input file is the enum, as I explained. But I can also reproduce it with other piece of code.
And the output will be in dist:
```
sap.ui.define([], function () {
  var SessionFailure;

  (function (SessionFailure) {
    SessionFailure[SessionFailure["INVALID_LOGIN_OR_PASSWORD"] = 0] = "INVALID_LOGIN_OR_PASSWORD";
  })(SessionFailure || (SessionFailure = {}));

  const __exports = {
    __esModule: true
  };
  __exports.SessionFailure = SessionFailure;
  return __exports;
});
```
(yarn install then yarn compile)

You can see there that `const` is still there after babel did its work. 
I hope you can easily check and reproduce my issue with this repo ! 

Thanks.
Guillaume

**Comment by GuillaumedesPommareSAP** [comment]
Hi @r-murphy !

Did you by chance had any chance to have a look to my issue ? I did not find a way to fix it so currently I am running with local clones of the project where I replaced in templates all const into var. This is not a very nice way to use it and it is only for development, of course I will need to work with the official package one day or the other.
I don't think ordering in babel has any impact for this specific issues, I tried several combinations and none worked.

Most probably you are more experienced than I am with babel, so in case you are able to show me where I am doing something wrong, please let me know !

Thanks.
Guillaume

**Comment by GuillaumedesPommareSAP** [comment]
Hi @r-murphy :)
Do you had any chance to have a look to my issue ? currently I am working on a quick fix that is ugly but works: I cloned the repos and replaced the templates with var instead of const. I am not able to find a way to fix it only with a babel config.

I created a sample project to test and reproduce, in case you have time to get a quick look.

Thanks.
Guillaume

**Comment by r-murphy** [comment]
@GuillaumedesPommareSAP  Thanks for the reproduction. I'm able to reproduce that as well. I think I understand why it's not being converted. I was hoping to come up with a good solution but have not had time. In the meantime, I think I will also output a couple places that I think will be impacted using `var`. I hope to have this done soon.

**Comment by r-murphy** [comment]
Please give v7.0.1 a try. It uses `var __exports = ` instead of `const __exports`. Let me know if there are still any `const` issues.

I also figured out how I can get babel to run transforms on the wrapping code. Unfortunately, it may require having babel re-traverse the entire file and call all the plugin visitors again. I may put it in as an option. I'm going to keep experimenting a bit to see if I can avoid the re-traversal.

**Comment by GuillaumedesPommareSAP** [comment]
Hello @r-murphy ,

This was also the local fix I made on my side and it fixes my issue.

Thanks ;)
