### ISSUE TITLE
namespacePrefix does not work with sourceRoot

### ISSUE THREAD

**Issue by Shingaz** [r-murphy/babel-plugin-transform-modules-ui5#38]
The documentation is not correct about the usage or the `sourceRoot` property. It show the property as relative to the babel configuration file:

https://github.com/r-murphy/babel-plugin-transform-modules-ui5/blob/f4554f7a304879961a1f9cd097c5f5acf3bfe712/README.md#L360-L368

The problem is that the filename is absolute in this function so `filename.startsWith(sourceRoot)` is always `false`

https://github.com/r-murphy/babel-plugin-transform-modules-ui5/blob/f4554f7a304879961a1f9cd097c5f5acf3bfe712/packages/plugin/src/classes/helpers/classes.js#L271-L286

Also, if we set the sourceRoot property to `path.join(__dirname, 'src')` the `dir` variable equals to `[""]` for files at the root. In the end, the namespace has an extra dot.

**Comment by winterkind** [comment]
I have a problem related to this. I am not using `namespacePrefix` but only `sourceRoot`, hoping to get file-based namespaces. But for the same reason given above, that does not work and I must set all namespaces manually.

**Comment by whitenrock** [comment]
Should be fixed with #55

**Comment by r-murphy** [comment]
PR merged and published in 7.0.5. Thanks @whitenrock
