### ISSUE TITLE
Babel 7 upgrade

### ISSUE THREAD

**Issue by o0Djeen0o** [r-murphy/babel-plugin-transform-modules-ui5#8]
Hi @r-murphy,

as Babel 7 is now available, do you plan a plugin upgrade in order to remove compatibility warning? 
https://babeljs.io/docs/en/v7-migration
I've never developped a Babel plugin, so not sure I can easily find what to do regarding breaking changes, but doesn't appear to have much issues, as I'm already using this plugin with babel 7 :-)

**Comment by o0Djeen0o** [comment]
Thanks for hard wordk! If you need some help to test your next version, do not hesitate to ask

**Comment by r-murphy** [comment]
Adding a note to this issue to that v7.0.0.rc is available. We've been using it in multiple apps in production for a few months now so I'll get the docs in order a bit and get it ready to release.

**Comment by r-murphy** [comment]
I've finally released 7.0.0. Thanks again for requesting this. 
No changes since 7.0.0-rc10.
