### ISSUE TITLE
"noWrapBeforeImport" option fails for imports without interop

### ISSUE THREAD

**Issue by akudev** [r-murphy/babel-plugin-transform-modules-ui5#80]
`noWrapBeforeImport` (back then called `minimalWrapping`) was introduced [here](https://github.com/r-murphy/babel-plugin-transform-modules-ui5/commit/584fbd9fcb2a1dad496a13a973f49b6c2f5cd4e6).

It works for [the testcase](https://github.com/r-murphy/babel-plugin-transform-modules-ui5/blob/master/packages/plugin/__test__/fixtures/min-wrap/min-wrap-simple.js) because an interop is needed and hence a "deconstructor" is [created](https://github.com/r-murphy/babel-plugin-transform-modules-ui5/blob/master/packages/plugin/src/modules/visitor.js#L90).
[Only with a deconstructor, `firstImport` is set](https://github.com/r-murphy/babel-plugin-transform-modules-ui5/blob/master/packages/plugin/src/modules/visitor.js#L140) and the deconstructors [replace the import in the body](https://github.com/r-murphy/babel-plugin-transform-modules-ui5/blob/master/packages/plugin/src/modules/visitor.js#L130).

The wrapping logic [only runs with `firstImport`](https://github.com/r-murphy/babel-plugin-transform-modules-ui5/blob/master/packages/plugin/src/modules/helpers/wrapper.js#L62) and uses the first deconstructor in the body as [marker for the first import](https://github.com/r-murphy/babel-plugin-transform-modules-ui5/blob/master/packages/plugin/src/modules/helpers/wrapper.js#L67).

With a file like this, however, there is no interop (because "sap/" is the default for no-interop), no "firstImport" and no marker in the body where the first import appears:
```ts 
const x = 1; // This should not be part of sap-ui-define - but wrongly is

import Button from "sap/m/Button";

const b = new Button(); // This gets wrapped
```

Hence the result is wrong - the first line is wrapped into the sap.ui.define call:
```ts
sap.ui.define(["sap/m/Button"], function (Button) {
  const x = 1; // This should not be part of sap-ui-define - but wrongly is

  const b = new Button(); // This gets wrapped
});
```

There is also NO WAY to figure out where the first import is (to only wrap the subsequent lines) because the import is completely removed from the body (replaced by zero "deconstructors").

I am willing to create a PR (actually trying to), but could use some guidance what approach would be accepted: e.g. mark the first node  after the first import by just setting some property and use this mark for knowing where to split the code? Or generate some dummy node to the body at the location of the first import, which is later on removed again? Any other way how this should be done?

~~By the way, would you agree that `noWrapBeforeImport` should actually be the default behavior in a new major version? It feels just more logical, I think.~~ *(see below)*

**Comment by codeworrior** [comment]
I'm not convinced that `noWrapBeforeImport` should be the default. IMO, this would be too much of a tribute to UI5's AMD legacy and not be aligned with ES modules (ESM). In ESM, declarative imports are always resolved before any code in the module is executed. So wrapping every statement from an ES module into an AMD definition IMO better reflects the ESM behavior. 

Someone familiar with TypeScript or ES modules will expect this behavior, not the behavior that `noWrapBeforeImport` shows. I admit that it's hard to notice the difference at runtime (to my understanding, this can happen only via side effects - something that can't be recommended anyhow), but when debugging, it still might come as a surprise.

I very well know the use cases for code in front of `sap.ui.define` (e.g. loader shims, disabling QUnit's autostart), but I wouldn't enable this via auto magic. If we in future manage to fully support ESM at runtime, ALL modules would have to be checked whether the then changed order of execution causes any harm or not.

I maybe would even make `noWrapBeforeImport` more explicit in the code (in a single source, e.g. via decorators). This would give a clear hint where to look at when enabling ESM at runtime in future.
